{% set version = "5.18.0" %}
{% set sha256 = "6c01be2306ec0c9656b59cb082eb7b90176c39506dd0f912b02e08298a553360" %}

package:
  name: libsbml-plus-packages
  version: {{ version }}

build:
  number: 0

source:  
  url: https://sourceforge.net/projects/sbml/files/libsbml/{{ version }}/stable/libSBML-{{ version }}-core-plus-packages-src.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - zlib
    - bzip2
    - libxml2
    
  host:
    - libxml2
    - zlib
    - bzip2
    
  run:
    - libxml2
    - zlib
    - bzip2

test:
  commands:
    - test -f ${PREFIX}/lib/libsbml.so  # [linux]

about:
  home: http://sbml.org/Software/libSBML
  license: LGPL
  license_file: 'LICENSE.txt'
  summary: LibSBML is a free, open-source programming library to help you read, write, manipulate, translate, and validate SBML files and data streams.
