{% set version = "5.20.0" %}
{% set sha256 = "400f1e1039ef0fc9addc99660a3a2559fefe9cb2c8315b1b488014b6101c438f" %}

package:
  name: libsbml-plus-packages
  version: {{ version }}

build:
  {% if CUSTOM_BUILD_NUMBER is defined %}
    number: {{ CUSTOM_BUILD_NUMBER }}
  {% else %}
    number: 0
  {% endif %}

source:  
  url: https://github.com/sbmlteam/libsbml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - zlib
    - bzip2
    - libxml2 {{ libxml2 }}
    
  host:
    - libxml2 {{ libxml2 }}
    - zlib
    - bzip2
    
  run:
    - libxml2 {{ libxml2 }}
    - zlib
    - bzip2

test:
  commands:
    - test -f ${PREFIX}/lib/libsbml.so  # [linux]

about:
  home: http://sbml.org/Software/libSBML
  license: LGPL
  license_file: 'LICENSE.txt'
  summary: LibSBML is a free, open-source programming library to help you read, write, manipulate, translate, and validate SBML files and data streams.
