name: Publish package

on:
  push:
  release:
    types: [created]
    
jobs:

  build_linux_defaults:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Install Conda
      run: |
        conda update conda
        conda update --all
        conda install conda-build anaconda-client conda-verify

    - name: Build
      run : |
        conda build .
        
    - name: Publish
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u vincent-noel /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2
        
    - name: Publish on CoLoMoTo
      if: github.event_name == 'release'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u colomoto /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2
       
  build_linux_conda_forge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Install Conda
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update --all
        conda install conda-build anaconda-client conda-verify

    - name: Build
      run : |
        CUSTOM_BUILD_NUMBER=1 conda build .
        
    - name: Publish
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u vincent-noel /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2
        
    - name: Publish on CoLoMoTo
      if: github.event_name == 'release'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u colomoto /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2
  
  build_macosx_defaults:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    
    - name: Downgrading XCode to 11.7
      run: |
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
        brew reinstall llvm            
        
    - name: Install Conda
      run: |
        conda update conda
        conda update --all
        conda install conda-build anaconda-client conda-verify

    - name: Build
      run : |
        conda build .
        
    - name: Publish
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2

    - name: Publish on CoLoMoTo
      if: github.event_name == 'release'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u colomoto /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2

        
  build_macosx_conda_forge:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    
    - name: Downgrading XCode to 11.7
      run: |
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
        brew reinstall llvm            
        
    - name: Install Conda
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update --all
        conda install conda-build anaconda-client conda-verify

    - name: Build
      run : |
        CUSTOM_BUILD_NUMBER=1 conda build .
        
    - name: Publish
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2

    - name: Publish on CoLoMoTo
      if: github.event_name == 'release'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u colomoto /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2
